# render.yaml
services:
  - type: web
    name: market-basket-backend
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MARKET_BASKET_DATASET_PATH
        value: ./datasets/processed_transactions.csv
      - key: PRODUCTION_FRONTEND_URL
        fromService:
          type: web
          name: market-basket-frontend
          property: host

  - type: web
    name: market-basket-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: market-basket-backend
          property: host